services:
  app:
    build: .
    container_name: arriendo-canchas-app
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    container_name: arriendo-canchas-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASS}"]
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
